### ISSUE TITLE
translateY(calc(env(safe-area-inset-top) + 12px)) scale(0.954023); in rootId it does not work correctly

### ISSUE THREAD

**Issue by rivaslive** [Temzasse/react-modal-sheet#1]
### THANK'S!
first of all, give thanks for the great work

### PROBLEM:
when I select rootId to do the iOS effect, the div generates excessive top margin, and it doesn't do the effect like this in the demo [](https://temzasse.github.io/react-modal-sheet/#/slack-message), I would like to know what I am doing wrong ?, embed my Tag `<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, viewport-fit=cover"/>`,
I am using Nextjs, and I try to use env () in the official site of next and it seems to have a similar behavior, maybe something specific to the DOMVirtual, maybe they should look for an alternative to that effect ...

![image](https://user-images.githubusercontent.com/39039038/94768477-c61be400-036c-11eb-9f35-1766f4127687.png)

env() CSS in Nextjs Page:

![image](https://user-images.githubusercontent.com/39039038/94768663-3e82a500-036d-11eb-814f-1a9b438c1264.png)

**Comment by Temzasse** [comment]
Thanks for reporting this! 🙏 

The problem here is that the iOS effect currently assumes that the root element height is 100% of the viewport height but this might not be true in certain cases like your Nextjs example. If the root element is much higher the scale calculation will produce incorrect looking result.

One way to fix this issue is to make sure the root element height is 100% the viewport height by applying these styles to the root:

```css
height: 100vh;
overflow: auto;
```

I will investigate if I could make the scale calculations for the iOS effect more robust somehow 🤔 🕵️

**Comment by Temzasse** [comment]
The way a webpage works by default is that the whole body of the page is scrollable which is not compatible with the iOS effect since there is no way to do the effect if you have scrolled down from the top of the page because the effect relies on transforming the root element. So in order to make the effect work properly you have to set the root element height to be exactly the same as the viewport height.

**Comment by rivaslive** [comment]
excellent, set my container height as you said and it works as desired
