### ISSUE TITLE
Unable to scroll on mobile devices

### ISSUE THREAD

**Issue by haripriya9209** [Temzasse/react-modal-sheet#122]
If the content is long, I am unable to scroll the content on mobile devices and able to see the scroll on desktop. Please let me know the fix for this. You can reproduce the issue here, try from mobile device: https://ung6zf.csb.app/

**Comment by doyoonkim12345** [comment]
it has a super simple way to fix it. just create a scroll container inside of the Sheet.Content.

then you can maybe easliy solve it

**Comment by Duderinooo** [comment]
@Temzasse As I understand the question it is: "How does the sheet know that swiping down is used to scroll a list or it is done with the purpose to close the modal sheet?" I tried it with a basic configuration and with a list on mobile it seems to be an issue.

**Comment by Temzasse** [comment]
Right, this question has been asked a few time in various issues and I'm not sure there is a bullet proof way to make scrolling play nicely with the drag gesture. They are by nature similar gestures and conflict with each other. Native apps have solved this somehow but I'm not sure if browsers have the built-in primitives to achieve the same thing 🤔 

If there is a way to do that with Framer Motion I'm definitely open to implementing it in to the library 😄

**Comment by pyrolass** [comment]
I fixed it by disabling drag on the Sheet.Content, note that you will lose the ability of drag to close.

**Comment by Temzasse** [comment]
There is now a new `Sheet.Scroller` component introduced in [v2](https://github.com/Temzasse/react-modal-sheet/releases/tag/v2.0.0). You can read more about how it is used [here](https://github.com/Temzasse/react-modal-sheet#scrolling-on-touch-devices).

It's probably not a perfect solution for all kinds of scrolling problems but I hope it helps with the most common use cases 🙂 

I'll keep this issue open for a while so that people can comment on how `Sheet.Scroller` is working for them.

**Comment by Temzasse** [comment]
`Sheet.Scroller` has been released for a while so closing this one.
