### ISSUE TITLE
Request: Close Sheet by dragging anywhere on the Container

### ISSUE THREAD

**Issue by fairhat** [Temzasse/react-modal-sheet#5]
Hey, thanks for the SSR update!

Is it possible to add this too?
Or expose some props to implement it myself?

**Comment by Temzasse** [comment]
I guess it would be possible to make the whole sheet draggable but there are some caveats to that:

- Scrolling would not work inside the sheet content anymore since framer-motion would capture all gestures and interpret them as dragging gestures.
- The same issue applies to tap gestures so all taps to buttons/checkboxes/etc would not work properly.
- Also things like native input range sliders would not work anymore.

If there is a way to implement this kind of draggability without breaking other tap/gesture based interactions I will definitely include it in the library.

Do you have some idea how this could be solved? I remember trying to figure this issue out when I initially created this lib but could not figure out a solution 😕

**Comment by Temzasse** [comment]
I decided to test if Framer Motion had updated it's way of handling gestures/taps inside draggable targets and it seems that nowadays it's possible to make the whole container draggable 🎉 (or maybe I just messed this up initially somehow 🙈)

I will test this is a bit more and add it to the lib if everything works OK.

**Comment by Temzasse** [comment]
@fairhat I added this feature to `1.1.0`. Please try it out and report any related issues 🙏

**Comment by fairhat** [comment]
works, thx!

**Comment by Mr-Fullstack** [comment]
can't get this working, this still works, would you have an example? please
