### ISSUE TITLE
Animation Not Working in Safari

### ISSUE THREAD

**Issue by ankur-kunaico** [Temzasse/react-modal-sheet#65]
Using it with FocusTrap

```

header: {
    opacity: 0,
    [theme.breakpoints.up('xl')]: {
      '& .react-modal-sheet-header': {
        height: '32px !important',
      },
      '& + .react-modal-sheet-content': {
        flex: '0 1 auto !important',
        overflow: 'visible !important',
      },
    },
  },
  content: {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'space-between',
    height: '100%',
    [theme.breakpoints.up('xl')]: {
      flexDirection: 'row',
      flexWrap: 'wrap',
    },

<Sheet
        isOpen={props.isOpen}
        onClose={() => props.setOpen(false)}
        snapPoints={width > widthBreakpoint ? [195] : [600]}>
        <Sheet.Container>
          <Sheet.Header className={classes.header} />
          <FocusTrap active={props.isOpen}>
            <Sheet.Content>
         {...Content}
            </Sheet.Content>
          </FocusTrap>
        </Sheet.Container>
        <Sheet.Backdrop />
      </Sheet>

```
Without Focus Trap Its working as expected
![ezgif com-gif-maker](https://user-images.githubusercontent.com/98843048/152906923-c1f4e9f8-cb32-4f57-aa39-5d471faffa9b.gif)

**Comment by Temzasse** [comment]
Interesting 🤔  This is probably due to the fact that I'm mapping over the children and passing them a custom key for `AnimatePresence` to work properly.

Can you try to put the `FocusTrap` between `Sheet` and `SheetContainer`? I'm doing that in my [A11ySheet demo](https://github.com/Temzasse/react-modal-sheet/blob/1decbbb8bfd84fc96003cbb30fa34eddd9cb5633/example/components/a11y/A11ySheet.tsx#L23) and worked okay.

```tsx
<Sheet>
  <FocusTrap>
    <SheetContainer>
      /* ... */
```

**Comment by stephanschubert** [comment]
@Temzasse I'm using your `A11ySheet` example but got the same issue.. **but** removing `restoreFocus` "fixes" it. Any idea what the culprit could be?
