### ISSUE TITLE
Is it possible to set snapshot as the content height value?

### ISSUE THREAD

**Issue by jungpaeng** [Temzasse/react-modal-sheet#69]
If the content height is 300, I would like to set the snapshot to 300.
Also, if the height of the content changes, I want to recognize it.

**Comment by jungpaeng** [comment]
It is similar to this issue. #46 
In `react-spring-bottom-sheet`, the minHeight argument is provided to the snapshot points

**Comment by milosjovancevic** [comment]
Hello folks, any updates on this? On my project I have 3 or 4 sheet's with different children(height). Any idea how to make children height dynamic?

**Comment by milosjovancevic** [comment]
Hello again,
After some time spent on figuring out solution (I failed to do so) I came by a pull request opened in repository #https://github.com/Temzasse/react-modal-sheet/pull/83 which solved the problem I had. Since my project deadline is soon I decided to fork the solution from this exceptional gentleman & developer https://github.com/nickgraffis and publish it in npm. Here is the link https://www.npmjs.com/package/@milosj/react-modal-sheet

After that you just add `useContentHeight` prop to your `Sheet` component and everything works like a charm.

Once more big thanks to @nickgraffis!

Regards,
Miloš

**Comment by Temzasse** [comment]
Sorry for taking so long to respond to this 😅

I took a look at the PR and it seems like a good change (just need to resolve some prop naming nit picks). I wonder if there are other things that should be taken into account for this to work as people expect 🤔 I guess we can publish the fix from Nick and figure out other things later if this change already helps people.

**Comment by Temzasse** [comment]
Sheet `detent` is now implemented in [v1.7.0](https://github.com/Temzasse/react-modal-sheet/releases/tag/v1.7.0). Please let me know if it doesn't solve your content height related issues 🙂
