### ISSUE TITLE
Type Error

### ISSUE THREAD

**Issue by shellord** [Temzasse/react-modal-sheet#80]
Getting an error like this when using TypeScript.

Property 'onViewportBoxUpdate' is missing in type '{ children: Element[]; }' but required in type 'Pick<MotionProps, "style" | "transformTemplate" | "transformValues" | "variants" | "transition" | "onViewportBoxUpdate" | "onBeforeLayoutMeasure" |

**Comment by playaz87** [comment]
Also getting this error i fixed it by implementing `onViewportBoxUpdate={() => {}}`

Whilst it does work, I have an issue on some devices where closing the sheet doesn't remove the `react-modal-sheet-container` div and leaves the backdrop covering the page rendering non-interactable.

**Comment by playaz87** [comment]
I'm using `framer-motion 6.3.3` and `react-modal-sheet 1.5.1`

**Comment by shellord** [comment]
@Temzasse same as @playaz87 
`framer-motion:^6.3.3` and `react-modal-sheet:^1.5.1`

**Comment by playaz87** [comment]
@Temzasse Any update on this?

**Comment by Temzasse** [comment]
Unfortunately I don't have bandwidth to investigate this issue at the moment.

To me this sounds like a Framer Motion related issue since I'm basically just using the types from `framer-motion` lib. Please check if there is a related issue in their repo. This could be an issue with your TS version as well 🤷‍♂️ 

My other hunch is that you might be having two versions of `framer-motion` installed. Are you using npm's `--legacy-peer-deps` to avoid getting duplicate peer deps?

**Comment by Johnrobmiller** [comment]
If, having installed the latest of both framer-motion and react-sheet-modal, react-sheet-modal has errors, then this is a bug within this library. Downgrading framer-motion is not a solution to this bug, but it's what I had to do in my case to get this library to work.

**Comment by playaz87** [comment]
@Johnrobmiller Which version of `framer-motion` worked for you?

**Comment by Temzasse** [comment]
I still have no clue what really caused the problem since everything works perfectly fine locally but when I build the lib the types have this extra `onViewportBoxUpdate` prop that comes out of thin air 😅 It was somehow related to me using `typeof` in the index file 🤷🏻‍♂️ 

Anyway, I think I found a way to fix the problem. Hopefully it works for you guys now 😊 

This should be fixed in the latest patch release `v1.5.2`.

**Comment by playaz87** [comment]
@Temzasse Thanks - can confirm I'm no longer getting the errors and it's no correctly working in Android Webview.
