### ISSUE TITLE
Content in Sheet.Content does not scroll

### ISSUE THREAD

**Issue by ahmedalashhab** [Temzasse/react-modal-sheet#91]
In my use case, the content of the sheet exceeds the vertical view of the sheet. When I try to scroll on a phone or PC, the sheet refuses to allow me to scroll down and view the rest of the content. On PC scroll works 70% of the time. However, on Android or iOS scroll does not work at all.

Upon disablingDrag the content became scrollable again, however I am no longer able to close the sheet.
Furthermore, I noticed that the page behind the sheet scrolls as well when I try to scroll the content in the sheet itself.

Is there a solution that would allow me to be able to scroll the content and to also close the sheet?

Thanks.

**Comment by billpull** [comment]
Based on my testing this is due to pointer events being disabled on the content div when drag is enabled but overriding them creates funky behavior with dragging.

**Comment by Temzasse** [comment]
I just released version [1.6.2](https://github.com/Temzasse/react-modal-sheet/releases/tag/v1.6.2) that should improve the body scroll locking behaviour so that the background will not scroll when the sheet is opened.

For the content scrolling/dragging issue I think there is really no other solution than to disable dragging for the content since the scroll and drag gestures are pretty much the same so Framer Motion has trouble distinguishing between the two which causes semi random behaviour when you have scrollable content inside the sheet. The header should still be draggable even if the dragging is disabled for the content.
